
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${license}"
issueTrackerURL="${issues_link}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="${banner_image}"
authors="${mod_authors}"
description='''${mod_description}'''
displayTest="MATCH_VERSION"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
